=== dwhodges2/Legacy-XML/flat_file_xml.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="resources">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="resource"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="resource">
    <xs:complexType>
          <xs:sequence>
            <xs:element name="id" type="xs:ID"/>
            <xs:element name="legacy_id" type="xs:string" minOccurs="0"/>
            <xs:element name="title" type="xs:string"/>
            <xs:element ref="authors"/>
            <xs:element name="content_type" type="xs:string"/>
            <xs:element name="resource_type" type="xs:string"/>
            <xs:element name="institution_id" type="nonNullStr"/>
            <xs:element name="abstract" type="xs:string" minOccurs="0"/>
            <xs:element ref="full_text" minOccurs="0"/>
            <xs:element name="pub_date" type="xs:date"/>
            <xs:element name="language" type="xs:string"/>
            <xs:element name="subject_id" minOccurs="0" maxOccurs="unbounded" type="nonNullStr"/>
            <xs:element ref="spatials" minOccurs="0"/>
            <xs:element name="journal_issue_id" minOccurs="0"/>
            <xs:element name="order" minOccurs="0"/>
            <xs:element ref="isbns" minOccurs="0"/>
            <xs:element ref="associated_ciao_resources" minOccurs="0"/>
            <xs:element ref="associated_external_resources" minOccurs="0"/>
          </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="associated_ciao_resources">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="associated_ciao_resource"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="associated_external_resources">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="associated_external_resource"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
  <xs:element name="authors">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="author_id"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
    
  
  <xs:element name="author_id">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="nonNullStr">
          <xs:attribute name="role" use="required" type="xs:string"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
 
  <xs:element name="full_text"  type="xs:anyType"/>
     
    
    
    
  <xs:element name="spatials">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="spatial"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
 
  <xs:element name="isbns">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="isbn"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
    
    <xs:element  type="xs:string" name="isbn"/>
  <xs:element name="spatial">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="id" type="nonNullStr"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
   <xs:element name="associated_ciao_resource">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="nonNullStr" name="ciao_id"/>
        <xs:element type="nonNullStr" name="order_id"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="associated_external_resource">
  <xs:complexType> 
<xs:sequence>    
  <xs:element name="id" type="nonNullStr"  />
</xs:sequence> 
  </xs:complexType>
  </xs:element>
  
  
  
  <xs:simpleType name="nonNullStr">
    <!--  define type to require some some non-whitespace text  -->
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
      <xs:pattern value=".*[^\s].*" />
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== dwhodges2/Legacy-XML/flat_file_template.xml
<?xml version="1.0"?>

<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="flat_file_xml.xsd">
  
  <resource>
    
    <!--  ID assigned by vendor with 'A' prefix. Also in filename. -->
    <id>A0002</id>
    
    <!--  Tile of work -->
    <title>Rethinking Modernity and National Identity in Turkey</title>
    
    <!--  Authors: Use author id from authority file, or create new with 'AU' prefix and add there;
          role attribute is required [Author | Editor]; Use 'Author' by default -->
    <authors>
      <author_id role="Author">45758</author_id>
      <author_id role="Author">45759</author_id>
    </authors>    
    
    <!--  Content types: Working Paper | Journal Article | Book | Policy Brief | 
          Case Study | Course Pack | Video | Ciao Focus   -->
    <content_type>Book</content_type>
    
    <!--  Resource types: Text | Moving Image | Collection  -->
    <resource_type>Text</resource_type>
    
    <!--  Institution: Use id from authority file, or create with new 'IN' prefix and add there -->
    <institution_id>806</institution_id>
    
    <!--  Abstract: Use from existing metadata; if none, pull first paragraph of full-text; otherwise leave empty -->
    <abstract>In Turkey and around the world today, we are witnessing the eclipse of the progressive and emancipatory discourse of modernity. Some of us view the spectacle with melancholyâ€”yet it has also produced a remarkably lively and pluralist climate in which new voices are being heard and deeply entrenched assumptions are being radically and, we believe, irreversibly challenged. At the center of the most heated theoretical debates in many disciplines is the question of whether it is possible to undertake a rigorous critique of the Enlightenment project of modernity without surrendering its liberating and humanist premises.</abstract>
    
    <!--  Full Text: Capture if any -->
    <full_text/>
    
    <!--  Pub Date: format yyyy-mm-dd -->
    <pub_date>1999-09-01</pub_date>
    
    <!--  Language: ISO language code [en | de | es | ...] -->
    <language>en</language>
    
    <!--  Subjects: Can be arbitrary number of subjects. 
          Match existing codes from authority file, or create new IDs using 'SU' prefix and add there  -->
    <subject_id>142</subject_id>
    
    <!--  Locations: Add ids as found in authority file; if none, create new ids with 'LO' prefix and add there -->
    <spatials>
      <spatial>
        <id>37</id>
      </spatial>
    </spatials>
    
    <!--  Journal Issue: Add ids as found in authority file; 
          if none, create new ids with 'JI' prefix and add there;
          order specifies article sequence within the journal issue-->
    <journal_issue_id></journal_issue_id>
    <order></order>
    
    <!--  ISBN: Add if any (i.e., if a book) -->
    <isbns>
      <isbn></isbn>
    </isbns>
    
    <!--  Associated resources: list of resources by id that appear as children of this resource; 
          order_id specifies list sorting -->
    <associated_ciao_resources>
      <associated_ciao_resource>
        <ciao_id></ciao_id>
        <order_id></order_id>
      </associated_ciao_resource>
    </associated_ciao_resources>
    
    <!--  External resources: Create unique ids with 'ER' prefix, and add to authority file; 
          details go in that file, use only id here; kind has two options: Link and YouTube; 
          for YouTube, the URL is only the video id string, which becomes a player embed on front end. -->
    <associated_external_resources>
      <associated_external_resource>
        <id></id>
      </associated_external_resource>
    </associated_external_resources>
  </resource>
</resources>
